### ISSUE TITLE
[Question] cudaErrorIllegalAddress - an illegal memory access was encountered

### ISSUE THREAD

**Issue by printffox** [tile-ai/tilelang#1275]
### Required prerequisites

- [x] I have read the documentation <https://tilelang.com>.
- [x] I have searched the [Issue Tracker](https://github.com/tile-ai/tilelang/issues) that this hasn't already been reported. (comment there if it has.)

### Questions

Recently, when I was trying to use the flash attention kernel written in tilelang, I found that it would report a memory error under some special input shapes. So I checked the official sample code: examples/flash_attention/example_mha_bwd_bhsd.py, and found that the official code would also report the same error under these special shapes. I guess it might be that the flashattn_bwd kernel messed up the memory during execution, but it's hard to find any mistake in the code that could cause this error.
My input shape is [64, 16, 572, 128], which indicates[batch, h, n_ctx, d_head] without casual_mask,and I'm quite sure this isn't the only shape that can trigger the memory error.
Previously, an official developer suggested that I could set a fixed random seed to ensure that this kind of memory error could be reproduced. However, in reality, regardless of whether I did this or not, these memory errors still occurred under these special shapes.But I still followed his advice and set the seed to 42.
```
def set_seed(seed=42):
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
```
### TraceBack
The detailed error messages are as follows. Although I don't think much useful information can be seen from these error reports.
```
Traceback (most recent call last):
  File "tilelang/examples/flash_attention/example_mha_bwd_bhsd.py", line 370, in <module>
    main(args.batch, args.h, args.n_ctx, args.d_head, args.causal)
  File "tilelang/examples/flash_attention/example_mha_bwd_bhsd.py", line 321, in main
    O.backward(dO, retain_graph=True)
  File "tilelang/jit/kernel.py", line 195, in __call__
    return self.torch_function(*args, **kwds)
  File "tilelang/jit/adapter/cython/adapter.py", line 485, in lambda_forward
    return self.cython_wrapper.forward([*args],
  File "tilelang/jit/adapter/cython/cython_wrapper.pyx", line 148, in tilelang.jit.adapter.cython.cython_wrapper.CythonKernelWrapper.forward
  File "tilelang/jit/adapter/cython/cython_wrapper.pyx", line 257, in tilelang.jit.adapter.cython.cython_wrapper.CythonKernelWrapper.forward
RuntimeError: Kernel call failed: flash_bwd_post_kernel: cudaErrorIllegalAddress - an illegal memory access was encountered
```
By the way, I tried tilelang==0.1.6.post1 and tilelang==0.1.6.post2, the memory error still exists. This matter has been bothering me for a long time. I hope someone has encountered or solved this problem and can offer me some solutions

**Comment by Rachmanino** [comment]
I'll take care of this when i have time :)

**Comment by printffox** [comment]
> I'll take care of this when i have time :)

Thank you. I think I have already found out where the root cause of this error message lies.
I attempted to disable the execution of the three kernels: `prep`, `bwd` and `post` respectively during the flash attention backward process, locking the error range to `bwd` and `post`. The common point among them is that the layout of dQ has been adjusted.
```
def make_dq_layout(dQ):
    # atomicAdd can not be vectorized, so we need to reorder dq to match the 8x8 gemm fragment
    return T.Layout(dQ.shape,
                    lambda b, h, l, d: [b, h, l // 8, d // 8, (d % 2), 4 * (l % 8) + (d % 8) // 2])
```
So I commented out the lines that use this function. Although this might cause performance degradation in normal execution scenarios, it solved my case. 
More cases need to be tested to verify that this function does indeed have problems.

P.S.
I have tested several other cases on two different GPUs. Now I think there is a high possibility that this function has problems. However, I have very little knowledge of the physical structure of GPUs and what so called `Layout`. Therefore, I'm just explaining the issue to you here, and hoping it won't mislead your work.
